import React from 'react'
import Logo from '../Images/iSHOP Logo.svg'

function TermConditions() {
    return (
    
        <div className='flex flex-col max-w-6xl m-auto mt-30 p-5  border-b-4'>
          <img src={Logo}className="md:h-10 h-6 my-10" alt="" />
          <h1 className='m-auto lg:text-8xl text-4xl'>Term & Conditions</h1>
          
          <h1 className='font-bold mt-10'>Ishop Terms of Use</h1>
            <div>
                  <p className='mb-5'>
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                  </p>
                  <p className='mb-5'>
                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology 
                  </p>
                  <p className='mb-5'>
                        The Platform is owned byIshop Internet Private Limited a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India (hereinafter referred to as "Ishop").
                  </p>
                  <p className='mb-5'>
                        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting withIshop Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, withIshop.
                  </p>
                  <p className='mb-5'>
                        For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems.Ishop allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall meanIshop Internet Private Limited.
                  </p>
                  <p>
                        When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.
                  </p>
            </div>
            <ol>
            <h1 className='font-bold'>Communications</h1>
                  <li >
                  When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise
                  </li>
                  </ol>
            <ol className='list-disc'>
                  <li>
                  All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services.Ishop does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not byIshop.
                  </li>
                  <ol>
                        <h1 className='font-bold'> Platform for Transaction and Communication</h1>
                              <p>The Platform is a platform that Users utilize to meet and interact with one another for their transactions.Ishop is not and cannot be a party to or control in any manner any transaction between the Platform's Users.
                              </p>
                              <h1 className='font-bold'>Henceforward:</h1>
                              <ol className='list-disc'>
                                    <li>
                                          All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services.Ishop does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers.
                                    </li> 
                                    <li>
                                          All discounts, offers (including exchange offers) are by the Seller/Brand and not byIshop.
                                          Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in the order by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.
                                    </li>
                                    <li>
                                         Ishop does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform.Ishop does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform.Ishop accepts no liability for any errors or omissions, whether on behalf of itself or third parties.
                                    </li>
                                         Ishop is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers.Ishop cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform.Ishop shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.
                                    <li>
                                         Ishop does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Platform and use Your best judgment in that behalf.
                                    </li>
                                    <li>
                                         Ishop does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.
                                    </li>
                                    <li>
                                          At no time shallIshop hold any right, title or interest over the products nor shallIshop have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers.Ishop is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.
                                    </li>
                                    <li>
                                          The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services.Ishop is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.
                                    </li>
                        </ol>
                  </ol>
            </ol>

            
                        
        </div>
     
      )
}
export default TermConditions;